### PR TITLE
[ATMO-649] Add user ssh keys

### PR DESCRIPTION
**Pull request by cdosborn**
Here is the ansible playbook to deploy user ssh keys.

See JIRA [ticket](https://pods.iplantcollaborative.org/jira/browse/ATMO-649).
Associated atmosphere [PR](https://github.com/iPlantCollaborativeOpenSource/atmosphere/pull/69).
Associated troposphere [PR](https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/215).

### CODE REVIEW

**Comment by steve-gregory** [comment]
:+1: LG2M. Thoughts @amercer1 ?

**Comment by amercer1** [comment]
It looks good so far. I just don't why we are putting this in root's folder as oppose to the user's. Since this going to be the last playbook that is run the users folder will be there. I don't get why we don't add their ssh keys there.

**Comment by cdosborn** [comment]
I was talking with edwin, its a convenience. I think it's okay, since it's an advanced configuration.

**Comment by amercer1** [comment]
Sounds good. Lets just make sure we come back to this at a later time to alter the deprecated authorized_key 2 file feature.
http://e.lvme.me/28hlutd.jpg

**Pull request merged**
